- name: generate current config set
  shell: /opt/vyatta/sbin/vyatta-config-gen-sets.pl > /tmp/gen-sets

- name: copy file gen-sets
  fetch: src=/tmp/gen-sets
         dest=configs/{{ inventory_hostname }}.gen-sets
         flat=yes

- name: copy config.boot
  fetch: src=/config/config.boot
         dest=configs/{{ inventory_hostname }}.config
         flat=yes

- name: delete conf files
  command: /bin/rm -f /tmp/gen-sets /tmp/config

